from dice import Dice

def create_dice():
    """
    This function creates a dice by passing a CREATE command
    :return: returns us a dice object
    """
    try:
        n_sides = int(input('Enter the number of sides a dice has: '))
        dice = Dice(n_sides)
    except ValueError:
        print('Must be an integer! \n')

    return dice


def roll_dice(dice):
    """
    Roll a dice by passing a ROLL command.
    :param dice: takes a previously created dice object.
            Returns a NameError message if dice object is not found
    :return: returns a list of roll values after a roll.
    """
    try:
        n_dice = int(input('How many dice do you have? '))
        n_roll = int(input('How many times to roll the dice? '))

    except ValueError:
        print('Must be an integer! \n')

    roll_count = []

    for x in range(n_roll):
        for i in range(n_dice):
            roll_dice = dice.roll_dice()
            roll_count.append(roll_dice)

    return roll_count


def memory(roll_hist, roll_count):
    """
    Memory function of the app.
    :param roll_hist: a list in which a program stores previous roll values
    :param roll_count: takes new values generated by each new dice roll
    :return: returns the list with previous saved roll values
    """
    previous_roll = roll_hist
    roll_hist.extend(roll_count)

    return previous_roll
